run_etl.sh: line 15: python3: command not found
